### PR TITLE
fix: custom post type tags excluded from archive pages

### LINKED ISSUE #115: Tags and Categories not Displaying Custom Post Type Posts
When a custom post type is generated, and a post is created from that custom post type, and tags or categories are applied to that post, the tag or category page for that particular tag or category does not display the custom post type post. Only standard post types are displayed on the tag or category page.

Tags and categories should pull in posts from custom post types in addition to standard post types. This means that when a tag or category is applied to a post created from a custom post type, that post should also appear on the respective tag or category page.

### PR DESCRIPTION
**Pull request by dustin-jw**
## Description

This fixes an issue where posts from custom post types were excluded from archive pages, such as by date, category, or tag, as well as the home page which lists recent posts. It requires a little bit of manual intervention from developers when they generate post types, but it's a one-liner, and instructions were updated to make it clear what to do on post type creation.

Closes #115 

## To Validate

1. Make sure all PR Checks have passed
2. Pull down this branch
3. Run `npm start`
4. Run `npm run generate:post-type` and answer the prompts to create a new custom post type, like "Recipes"
5. Confirm that the output of the generator includes a message about how to enable the post type on archive pages
6. Follow the instructions in the message/comments to add the post type to the `enable_custom_posts_in_archives` function
7. Add some categories and/or tags to regular posts
8. Create posts for the new post type and give some of them the same tags and categories as the other posts
9. Check the home page and confirm that your custom posts are listed along with regular posts
10. Check tag archives (`?tag=<tag-slug>`) to confirm all posts with that tag are rendered
11. Check category archives (`?cat=<category-id>`) to confirm all posts with that category are rendered
12. Check date archives (`?m=2023`) to confirm all posts authored in the given year are rendered
13. Check custom post type archives (`?post_type=<post-slug>`) and confirm that _only_ posts from the custom post type are rendered

### CODE REVIEW

File: src/php/inc/custom-post-types/recipe.php [hunk 1]
```diff
@@ -0,0 +1,40 @@
+<?php
```
Comment (robtarr) [inline src/php/inc/custom-post-types/recipe.php:1]: Is this file supposed to be checked in?

File: src/php/inc/setup-queries.php [hunk 2]
```diff
@@ -10,8 +10,34 @@
  * @return array
  */
 function sb_query_vars_filter( $vars ) {
-	$vars[] = 'example_var'; // e.g. allow ?example_var="test" in url.
+	// Allow custom query params in URL.
+	// e.g. $vars[] = 'example_var'; to allow ?example_var=test in URL.
 	return $vars;
 }
-
 add_filter( 'query_vars', 'sb_query_vars_filter' );
```
Comment (robtarr) [inline src/php/inc/setup-queries.php:17]: Since this function isn't doing anything, do we want to comment out the `add_filter` call as well?

File: src/php/inc/theme-scripts.php [hunk 3]
```diff
@@ -9,9 +9,10 @@
  * Enqueue scripts and styles.
  */
 function sparkpress_theme_scripts() {
-	$example_data = array( '1', '2', '3' );
 	wp_enqueue_script( 'sparkpress-theme-script', get_template_directory_uri() . '/js/scripts.js', array(), _S_VERSION, true );
-	// Defines an `example` JavaScript variable, within the sparkpress-theme-script, equal to $example_data.
-	wp_localize_script( 'sparkpress-theme-script', 'example', $example_data );
+
+	// You can also define global variables that get appended to an enqueued script.
```
Comment (robtarr) [inline src/php/inc/theme-scripts.php:14]: 🏆

File: src/php/inc/custom-post-types/recipe.php (hunk 1 above)
Comment (dustin-jw) [reply src/php/inc/custom-post-types/recipe.php]: Ope, good catch, that must've snuck in while I was testing things out. Removed in https://github.com/sparkbox/sparkpress-wordpress-starter/pull/124/commits/7b89a84908a9625bce8c404d42c5d7e46b84618f

File: src/php/inc/setup-queries.php (hunk 2 above)
Comment (dustin-jw) [reply src/php/inc/setup-queries.php]: Good call, updated in https://github.com/sparkbox/sparkpress-wordpress-starter/pull/124/commits/c5077f2a06aba090b7ff0cf795b88635d720dd80

**Review by robtarr — APPROVED** [review]
Thumbs Up
