### PR TITLE
fix: minor accessibility issues

### LINKED ISSUE #69: Remove incorrect/unnecessary ARIA roles
There are a few roles that are either redundant with the implicit roles for the elements they're on, or they're used incorrectly. For example, the `h1` has a role of `banner`, which is incorrect, as [banner](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/banner_role) is the implicit role of the `header` element and is meant to apply to global site headers, not headings. Similarly, the `article` tag is given a role of `main`, despite there being a `main` element wrapping it already. Lastly, the `nav` element has a role of `navigation`, which isn't wrong, but it is redundant. More useful for accessibility would be to set `aria-label="Main"` on that element.

### PR DESCRIPTION
**Pull request by dustin-jw**
## Description

This fixes a handful of accessibility issues that are not necessarily blockers, but not ideal. That includes:

- Removing improper ARIA roles
- Adding `aria-label` to different `nav` elements to distinguish between them
- Fixing up the accessibility tree
- Updating heading levels so that the home page link is not the `h1` and that we don't skip straight to `h4`

Closes #69 

## To Validate

1. Make sure all PR Checks have passed
2. Pull down this branch
3. Run `npm start`
4. Go through all non-admin pages and run Lighthouse and/or axe DevTools on each page, confirming that there are no automatically detected issues
5. Inspect the accessibility tree and confirm that the document is structured in a way that makes sense and that elements have the roles and accessible names that you would expect

### CODE REVIEW

File: src/php/index.php [hunk 1]
```diff
@@ -12,9 +12,10 @@
 
 $context          = Timber\Timber::context();
 $context['posts'] = new Timber\PostQuery();
-$context['foo']   = 'bar';
```
Comment (rise-erpelding) [inline src/php/index.php:15]: Oh, good catch, I'd seen this and was wondering if we'd want to remove it.

File: src/php/views/base.twig [hunk 2]
```diff
@@ -1,26 +1,27 @@
...
 
-			{% if post.title %}
-        <div class="obj-width-limiter">
-          {# equivalent to the_title() #}
-          <h1>{{ post.title }}</h1>
-        </div>
-      {% endif %}
+	{% if post.title %}
+		<div
+			class="obj-width-limiter">
```
Comment (rise-erpelding) [inline src/php/views/base.twig:7]: Is there a reason the `class` attribute is on a different line here?

**Review by rise-erpelding — APPROVED** [review]
This made a huge difference in the Axe DevTools testing especially! Nice work! The only automatically detected issue I see there is associated with the `wpadminbar`, so I don't think we need to worry about that.

I did leave one question about a line break but it doesn't impact the accessibility either way.

File: src/php/views/base.twig (hunk 2 above)
Comment (dustin-jw) [reply src/php/views/base.twig]: That was automatic formatting from a Twig extension I had installed in my editor. I agree that it doesn't make much sense, so I disabled it and updated that line.
